# Generated by Django 4.2.5 on 2024-01-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_date',
        ),
    ]
